# Generated by Django 2.2 on 2019-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
