# Generated by Django 2.2 on 2019-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_myitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='myitem',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
